---
all:
  children:
    jenkins:
      hosts:
        jenkins-server:
          ansible_host: 10.0.0.1 # Replace with actual Jenkins server IP
          ansible_user: ubuntu
          ansible_ssh_private_key_file: ./keys/aws-key.pem
          
    monitoring:
      hosts:
        prometheus-server:
          ansible_host: 10.0.0.2 # Replace with actual Prometheus/Grafana server IP
          ansible_user: ubuntu
          ansible_ssh_private_key_file: ./keys/aws-key.pem
          
    database:
      hosts:
        db-server:
          ansible_host: 10.0.0.3 # Replace with actual Database server IP
          ansible_user: ubuntu
          ansible_ssh_private_key_file: ./keys/aws-key.pem
          
    app:
      hosts:
        app-server:
          ansible_host: 10.0.0.4 # Replace with actual Application server IP
          ansible_user: ubuntu
          ansible_ssh_private_key_file: ./keys/aws-key.pem
          
  vars:
    ansible_python_interpreter: /usr/bin/python3
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'